### PR TITLE
update dependencies

### LINKED ISSUE #26: update dependencies

### PR DESCRIPTION
**Pull request by cxoltero**
resolves #26

### CODE REVIEW

**Comment by obuckley-kenzan** [comment]
Can one of the admins verify this patch?

**Comment by thescientist13** [comment]
ok to test

**Comment by obuckley-kenzan** [comment]
ok to test

**Comment by thescientist13** [comment]
ok to test

**Comment by thescientist13** [comment]
I guess this would be a breaking change then since it is causing the build to fail?  However, it does seem more related to our general musings happening here though
https://github.com/kenzanlabs/keystone/issues/34#issuecomment-272212247

**Comment by thescientist13** [comment]
the Jenkins configuration wasn't set to install Node v4.  Let's see what happens now.

ok to test

**Comment by thescientist13** [comment]
ok to test

**Pull request merged**
